#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; TMP_WORK_DIR="$2"; REV="$3"

dokku_log_info2 "Looking for .dokku-overlay"

[[ ! -f "$TMP_WORK_DIR/.dokku-overlay" ]] && exit

dokku_log_info2 "Overlay plugin detected"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  src_dir="${line[1]}"
  dokku_log_info2 "Copying directory ./$src_dir into app"

  cp -rf "$TMP_WORK_DIR/$src_dir" "$TMP_WORK_DIR"
  exit
done 10<"$TMP_WORK_DIR/.dokku-overlay"

dokku_log_info2 "The application $APP is not defined in .dokku-overlay!"
exit 1
